### ISSUE TITLE
Cannot get the same retrieval split

### ISSUE THREAD

**Issue by BrandonHanx** [amzn/fashion-attribute-disentanglement#5]
please refer to https://github.com/amzn/fashion-attribute-disentanglement/issues/2

**Comment by BrandonHanx** [comment]
Actually, I cannot understand why you cannot share the retrieval split. Otherwise, people cannot do comparisons with you.

**Comment by lorisbaz** [comment]
This repository releases the necessary to replicate the results of the Attribute-Driven Disentangled Encoder (ADDE) as well as the model for attribute manipulation (ADDE-M), as explained in the readme file.

Unfortunately, we do not plan to release the splits for outfit retrieval. We suggest to reach out to the authors of the original paper "Fashion outfit complementary item retrieval, CVPR 2020".
